services:
  fastapi:
    build: .
    container_name: fastapi-server
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    env_file:
      - .env

    streamlit:
      build: .
      container_name: streamlit-app
      working_dir: /code/streamlit-app
      command: >
        streamlit run test_app.py
        --server.address=0.0.0.0
        --server.port=8501
        --server.headless=true
        --server.enableCORS=false
        --server.enableXsrfProtection=false
      ports:
        - "8502:8501"
      volumes:
        - .:/code
      env_file:
        - ./streamlit-app/.env
      depends_on:
        - fastapi