"""init tables

Revision ID: b1413d2b74d1
Revises: 
Create Date: 2026-03-13 12:40:31.749937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1413d2b74d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_matches_article_id_keyword_id_key'), 'article_matches', type_='unique')
    op.create_unique_constraint('uq_article_matches_article_keyword', 'article_matches', ['article_id', 'keyword_id'])
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_crawl_runs_keyword_started_at'), table_name='crawl_runs')
    op.create_index('ix_crawl_runs_keyword_started_at', 'crawl_runs', ['keyword_id', 'started_at'], unique=False)
    op.add_column('credit_transactions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_credit_tx_user_created_at'), table_name='credit_transactions')
    op.create_index('ix_credit_tx_user_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.drop_column('credit_wallets', 'updated_at')
    op.add_column('email_deliveries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_email_status_sent_at'), table_name='email_deliveries')
    op.create_index('ix_email_status_sent_at', 'email_deliveries', ['status', 'sent_at'], unique=False)
    op.drop_index(op.f('ix_email_user_created_at'), table_name='email_deliveries')
    op.create_index('ix_email_user_created_at', 'email_deliveries', ['user_id', 'created_at'], unique=False)
    op.add_column('feedbacks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('importance_scores', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_importance_scores_user_current'), table_name='importance_scores')
    op.create_index('ix_importance_scores_user_current', 'importance_scores', ['user_id', 'is_current', 'created_at'], unique=False)
    op.drop_index(op.f('ix_jobs_user_created_at'), table_name='jobs')
    op.create_index('ix_jobs_user_created_at', 'jobs', ['user_id', 'created_at'], unique=False)
    op.add_column('keywords', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('keywords_user_id_keyword_text_key'), 'keywords', type_='unique')
    op.create_unique_constraint('uq_keywords_user_keyword_text', 'keywords', ['user_id', 'keyword_text'])
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ux_reports_user_type_period'), table_name='reports')
    op.drop_index(op.f('ix_reports_user_created_at'), table_name='reports')
    op.create_index('ix_reports_user_created_at', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_reports_user_type_period', 'reports', ['user_id', 'report_type', 'period_start', 'period_end'])
    op.add_column('summaries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_summaries_article_language'), table_name='summaries')
    op.create_index('ix_summaries_article_language', 'summaries', ['article_id', 'language', 'created_at'], unique=False)
    op.add_column('translations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('translations_article_id_source_lang_target_lang_engine_name_key'), 'translations', type_='unique')
    op.create_unique_constraint('uq_translations_article_lang_engine', 'translations', ['article_id', 'source_lang', 'target_lang', 'engine_name'])
    op.drop_constraint(op.f('user_tokens_user_id_provider_key'), 'user_tokens', type_='unique')
    op.create_unique_constraint('uq_user_tokens_user_provider', 'user_tokens', ['user_id', 'provider'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_constraint('uq_user_tokens_user_provider', 'user_tokens', type_='unique')
    op.create_unique_constraint(op.f('user_tokens_user_id_provider_key'), 'user_tokens', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_translations_article_lang_engine', 'translations', type_='unique')
    op.create_unique_constraint(op.f('translations_article_id_source_lang_target_lang_engine_name_key'), 'translations', ['article_id', 'source_lang', 'target_lang', 'engine_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('translations', 'updated_at')
    op.drop_index('ix_summaries_article_language', table_name='summaries')
    op.create_index(op.f('ix_summaries_article_language'), 'summaries', ['article_id', 'language', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('summaries', 'updated_at')
    op.drop_constraint('uq_reports_user_type_period', 'reports', type_='unique')
    op.drop_index('ix_reports_user_created_at', table_name='reports')
    op.create_index(op.f('ix_reports_user_created_at'), 'reports', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ux_reports_user_type_period'), 'reports', ['user_id', 'report_type', 'period_start', 'period_end'], unique=True)
    op.drop_column('reports', 'updated_at')
    op.drop_constraint('uq_keywords_user_keyword_text', 'keywords', type_='unique')
    op.create_unique_constraint(op.f('keywords_user_id_keyword_text_key'), 'keywords', ['user_id', 'keyword_text'], postgresql_nulls_not_distinct=False)
    op.drop_column('keywords', 'updated_at')
    op.drop_index('ix_jobs_user_created_at', table_name='jobs')
    op.create_index(op.f('ix_jobs_user_created_at'), 'jobs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_importance_scores_user_current', table_name='importance_scores')
    op.create_index(op.f('ix_importance_scores_user_current'), 'importance_scores', ['user_id', 'is_current', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('importance_scores', 'updated_at')
    op.drop_column('feedbacks', 'updated_at')
    op.drop_index('ix_email_user_created_at', table_name='email_deliveries')
    op.create_index(op.f('ix_email_user_created_at'), 'email_deliveries', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_email_status_sent_at', table_name='email_deliveries')
    op.create_index(op.f('ix_email_status_sent_at'), 'email_deliveries', ['status', sa.literal_column('sent_at DESC')], unique=False)
    op.drop_column('email_deliveries', 'updated_at')
    op.add_column('credit_wallets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_credit_tx_user_created_at', table_name='credit_transactions')
    op.create_index(op.f('ix_credit_tx_user_created_at'), 'credit_transactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('credit_transactions', 'updated_at')
    op.drop_index('ix_crawl_runs_keyword_started_at', table_name='crawl_runs')
    op.create_index(op.f('ix_crawl_runs_keyword_started_at'), 'crawl_runs', ['keyword_id', sa.literal_column('started_at DESC')], unique=False)
    op.drop_column('articles', 'updated_at')
    op.drop_constraint('uq_article_matches_article_keyword', 'article_matches', type_='unique')
    op.create_unique_constraint(op.f('article_matches_article_id_keyword_id_key'), 'article_matches', ['article_id', 'keyword_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
